// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v2

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmbInsCondition) DeepCopyInto(out *AmbInsCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmbInsCondition.
func (in *AmbInsCondition) DeepCopy() *AmbInsCondition {
	if in == nil {
		return nil
	}
	out := new(AmbInsCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmbassadorInstallation) DeepCopyInto(out *AmbassadorInstallation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmbassadorInstallation.
func (in *AmbassadorInstallation) DeepCopy() *AmbassadorInstallation {
	if in == nil {
		return nil
	}
	out := new(AmbassadorInstallation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AmbassadorInstallation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmbassadorInstallationList) DeepCopyInto(out *AmbassadorInstallationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AmbassadorInstallation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmbassadorInstallationList.
func (in *AmbassadorInstallationList) DeepCopy() *AmbassadorInstallationList {
	if in == nil {
		return nil
	}
	out := new(AmbassadorInstallationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AmbassadorInstallationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmbassadorInstallationSpec) DeepCopyInto(out *AmbassadorInstallationSpec) {
	*out = *in
	if in.HelmValues != nil {
		in, out := &in.HelmValues, &out.HelmValues
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmbassadorInstallationSpec.
func (in *AmbassadorInstallationSpec) DeepCopy() *AmbassadorInstallationSpec {
	if in == nil {
		return nil
	}
	out := new(AmbassadorInstallationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmbassadorInstallationStatus) DeepCopyInto(out *AmbassadorInstallationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]AmbInsCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeployedRelease != nil {
		in, out := &in.DeployedRelease, &out.DeployedRelease
		*out = new(AmbassadorRelease)
		**out = **in
	}
	in.LastCheckTime.DeepCopyInto(&out.LastCheckTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmbassadorInstallationStatus.
func (in *AmbassadorInstallationStatus) DeepCopy() *AmbassadorInstallationStatus {
	if in == nil {
		return nil
	}
	out := new(AmbassadorInstallationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmbassadorRelease) DeepCopyInto(out *AmbassadorRelease) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmbassadorRelease.
func (in *AmbassadorRelease) DeepCopy() *AmbassadorRelease {
	if in == nil {
		return nil
	}
	out := new(AmbassadorRelease)
	in.DeepCopyInto(out)
	return out
}
