---
apiVersion: getambassador.io/v2
kind: AmbassadorInstallation
metadata:
  name: ambassador
spec:
  installOSS: true
  helmValues:
    deploymentTool: amb-oper-kind
    replicaCount: 1
    nodeSelector:
      ingress-ready: "true"
    service:
      type: NodePort
      ports:
        - name: http
          port: 80
          targetPort: 8080
          protocol: TCP
        - name: https
          port: 443
          targetPort: 8443
          protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: klipper-lb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: klipper-permissions
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "watch", "list", "write", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: klipper-permissions-binding
subjects:
  - kind: ServiceAccount
    name: klipper-lb
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: klipper-permissions
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: svclb-klipper
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: svclb-klipper
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: svclb-klipper
    spec:
      serviceAccountName: klipper-lb
      containers:
        - env:
            - name: SRC_PORT
              value: "80"
            - name: DEST_PROTO
              value: TCP
            - name: DEST_PORT
              value: "80"
            - name: DEST_ADDR
              value: "ambassador.ambassador"
          image: inercia/klipper-lb:latest
          imagePullPolicy: Always
          name: lb-port-80
          ports:
            - containerPort: 80
              hostPort: 80
              name: lb-port-80
              protocol: TCP
          resources: {}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - env:
            - name: SRC_PORT
              value: "443"
            - name: DEST_PROTO
              value: TCP
            - name: DEST_PORT
              value: "443"
            - name: DEST_ADDR
              value: "ambassador.ambassador"
          image: inercia/klipper-lb:latest
          imagePullPolicy: Always
          name: lb-port-443
          ports:
            - containerPort: 443
              hostPort: 443
              name: lb-port-443
              protocol: TCP
          resources: {}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
